services:
  backend:
    image: node:20
    container_name: server
    working_dir: /src/app
    volumes:
      - ./backend:/src/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 0.0.0.0
    ports:
      - 5000:5000
    command: npm run dev
  frontend:
    image: node:20
    depends_on:
      - backend
    container_name: client
    working_dir: /src/app
    command: "yarn start --host 0.0.0.0"
    volumes:
      - ./frontend:/src/app
      - /app/node_modules
    ports:
      - 4200:4200

